
title: Joel Hill
author: Joel Hill
email: joel.hill.87@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A repository for all of my long form thoughts. 
  I write about technology, programing, and electronic projects (but really anything goes). 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: true # set to true to show excerpts on the homepage

# theme settings
minima:
  social_links:
    twitter: joelghill
    github: joelghill
    rss: rss

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md

# Build settings
theme: minima
plugins:
 - jekyll-feed
 - jekyll-seo-tag

google_analytics: UA-33348943-2

disqus:
  shortname: joelhill
  url: http://joelghill.github.io

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
